fix: invalid host header issue on codesandbox
merkle-open/gondel pull request #95
Opened 2023-10-18 13:12 UTC by stefanibus

solves Issue #94 (The examples no longer work in CodeSandbox environments.)

We need to add the allowedhosts-flag to devServer-settings for webpack.config:

devServer-config to solve "Invalid Host header Issue" on CodeSandBox:

https://github.com/codesandbox/codesandbox-client/issues/3392 and

https://stackoverflow.com/a/43647767 and
  https://codesandbox.io/docs/learn/repositories/task#configuring-task-ports

https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#firewall

https://webpack.js.org/configuration/dev-server/#devserverallowedhosts

firewall: false, // failed while testing

disableHostCheck: true, // failed while testing

allowedHosts: This flag finally solved it

## Purpose of this pull request? 

* Documentation update
* Bug fix
* Enhancement
* Other... Please describe

## What changes did you make?

## Does this pull request introduce a breaking change?

## Is there anything you'd like reviewers to focus on?

2023-10-19 12:57 UTC, ernscht requested changes
Great, let's give it a try. Thank you very much.

Can you take care of the little changes?

2023-10-20 08:19 UTC, stefanibus commented on examples/find-components/.codesandbox/tasks.json
> +	// These tasks will run in order when initializing your CodeSandbox project.
Codesandbox auto-created tasks.json for me. I  used the json-file as it is and left it completely unchanged. I did not create those comments inside of the tasks.json. I guess codesandbox is using a minify-service to remove comments from the json documents before parsing the actual json string. I removed all comments from all files now to comply with the specs.

2023-10-20 08:19 UTC, stefanibus commented on .github/contributing.md
> +All our CodeSandBox-Samples are [synced-templates](https://codesandbox.io/docs/learn/sandboxes/synced-templates) with our GitHub-repo: they will update automatically, once our repositories main branc
done! Thank you!

2023-10-23 08:53 UTC, ernscht approved these changes

2023-10-23 08:53 UTC, merged